# ░░░░░░░░░░░░░░░   LotteryPlus, By Momocraft♥   ░░░░░░░░░░░░░░░
#  Spigot: https://www.spigotmc.org/resources/entityplus.85995/
#  Wiki: https://github.com/momoservertw/LotteryPlus/wiki
# ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
Config-Version: 4
Debugging: false
Check-Updates: true

# Randomly select a reward for player.
# You can use ItemJoin to create one-use items.
# Or using with menu plugins like ChestCommands or BossShop.
# Lottery command: /lotteryplus lottery <groupName>
# More information: https://github.com/momoservertw/LotteryPlus/wiki/Lottery
Lottery:
  Enable: false
  Settings:
    Features:
      # Executing lottery when player broke a lucky block.
      Lucky-Block: false
      # The proportion of different player groups.
      # Permission: lotteryplus.lottery.chancegroup.GROUP
      Priority:
        defualt: 0
        vip: 1
        mvp: 2
    # Add logs when lottery.
    Log: true
  Groups:
    ticket:
      Enable: false
      Groups:
        Normal:
          Enable: true
          Chance: 0.5
          Commands:
            - "message: You win iron_ingot x16.{n}console: give %player% iron_ingot 16"
            - "message: You win gold_inot x16.{n}console: give %player% gold_inot 16"
            - "message: You win iron_ingot x16.{n}console: money give %player% %random_number%500%"
        Rare:
          Enable: true
          Chance: 0.375
          Commands:
            - "broadcast: %player% win iron_ingot x16.{n}console: give %player% iron_ingot 32"
            - "broadcast: %player% win gold_inot x16.{n}console: give %player% gold_inot 32"
            - "broadcast: %player% win iron_ingot x16.{n}console: money give %player% %random_number%1000%"
    random_head:
      Enable: false
      Groups:
        online_players:
          Enable: true
          # Setting difference change for groups.
          # You have to set their "Priority" above.
          Chance:
            default: 0.70
            vip: 0.65
          Commands:
            - "console: give %player% minecraft:player_head{SkullOwner:\"%random_player%\"} 1"
    lucky_block:
      Enable: false
      Settings:
        Lucky-Block:
          # More skull(copy the Value): https://minecraft-heads.com/custom-heads
          Skull-Textures: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzlkMWVmNGMxNTNiZGU4YTdiMDhmOTJjMGM0Yjc5ZmRjMmZjYjU3ZjgzYTMxYTgyMjljNjJhYzc1ZjFmMGEzMSJ9fX0="
      Groups:
        Normal:
          Enable: true
          Chance: 0.8
          Commands:
            - "custom: awards, Normal award{n}console: give %player% IRON_INGOT 1;"