# --{ =-=-=-=-=-=-=-=-=-= LotteryPlus's Configuration Settings, by Momocraft =-=-=-=-=-=-=-=-=-= }--
# Wiki: https://github.com/momoservertw/LotteryPlus/wiki
Config-Version: 1
Check-Updates: true
Debugging: false

General:
  # - "custom: congratulate, Lottery ticket, Jackpot, $10,000"
  Custom-Commands:
    reward: "message: &f &6&lReward&c✤ &f%cmd_arg1%"
    awards: "message: &d✧ &f%cmd_arg1% &d✧"
    cgl: "broadcast: &6Congratulate &e%player% &6use &f%cmd_arg1% &8- &6Get the %cmd_arg2% &7<&f%cmd_arg3%&7>"
    money: "console: money give %player% %cmd_arg1%"

Lottery:
  Enable: true
  Groups:
    ticket:
      Enable: false
      Normal:
        Enable: true
        Chance: 0.5
        Commands:
          - "custom: reward, Normal;console: money give %player% %random_number%500%"
      Rare:
        Enable: true
        Chance: 0.375
        Commands:
          - "custom: reward, Rare;console: money give %player% 1000"
      Super-Rare:
        Enable: true
        Chance: 0.06
        Commands:
          - "custom: reward, Super Rare;console: money give %player% 3000"
      Ultra-Rare:
        Enable: true
        Chance: 0.03
        Commands:
          - "custom: reward, Ultra Rare;console: money give %player% 10000"
      Mysterious:
        Enable: true
        Chance: 0.025
        Commands:
          - 'custom: cgl, Mysterious, Lottery Ticket, &cRandom Head;console: give %player% minecraft:player_head{SkullOwner:"%random_player%"} 1'
    head_random:
      Enable: false
      online:
        Enable: true
        Chance: 20
        Commands:
          - 'custom: cgl, Random Head, Online Players, Player Head;console: give %player% minecraft:player_head{SkullOwner:"%random_player%"} 1'
      staff:
        Enable: true
        Chance: 6
        Commands:
          - 'custom: cgl, Random Head, Staff, yoyo880603s Head;console: give %player% minecraft:player_head{SkullOwner:"yoyo880603"} 1'
          - 'custom: cgl, Random Head, Staff, PTL_piepiepigs Head;console: give %player% minecraft:player_head{SkullOwner:"PTL_piepiepig"} 1'
          - 'custom: cgl, Random Head, Staff, LOTT_0s Head;console: give %player% minecraft:player_head{SkullOwner:"LOTT_0"} 1'
          - 'custom: cgl, Random Head, Staff, PowLim_Deitys Head;console: give %player% minecraft:player_head{SkullOwner:"PowLim_Deity"} 1'
      owner:
        Enable: true
        Chance: 2
        Commands:
          - 'custom: cgl, Random Head, Server Owner, AllByes Head;console: give %player% minecraft:player_head{SkullOwner:"AllBye"} 1'
          - 'custom: cgl, Random Head, Server Owner, huangge0513s Head;console: give %player% minecraft:player_head{SkullOwner:"huangge0513"} 1'

Message:
  prefix: '&f'
  noPermission: '&cYou do not have permission to use that command!'
  configReload: '&aConfiguration(s) Reloaded!'
  unknownCommand: '&cUnknown command, See &e/LotteryPlus help &cfor a list of commands.'
  LotteryPlus:
    Commands:
      title: "&8▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩ &d&lLotteryPlus &8▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩"
      help: "&a/lotteryplus help &8- &7This help menu."
      reload: "&a/lotteryplus reload &8- &7Reloads config file."
      version: "&f/lotteryplus version &8- &7Checks the plugin version and updates."
      lottery: "&f/lotteryplus lottery <rewardName> &8- &7Lottery the rewards."