name: LotteryPlus
main: tw.momocraft.lotteryplus.LotteryPlus
author: Momocraft
api-version: 1.13
version: 1.0.7
description: Make your own capsule!
softdepend: [Vault, PlaceHolderAPI]

commands:
  lotteryplus:
    description: Displays main command menu.
    permission: lotteryplus.use
    aliases: [ltp]
    usage: |
      /lotteryplus

permissions:
  lotteryplus.*:
    description: Allows use of all commands and feature.
    default: op
    children:
      lotteryplus.use: true
      LotteryPlus.command.*: true
      lotteryplus.lottery.*: true
  lotteryplus.use:
    description: Allows use of basic commands.
    default: true
  lotteryplus.command.*:
    description: Allows use all commands.
    default: op
    children:
      lotteryplus.command.reload: true
      lotteryplus.command.version: true
      lotteryplus.command.lottery: true
  lotteryplus.command.reload:
    description: Allows use of /LotteryPlus command reload.
    default: op
  lotteryplus.command.version:
    description: Allows use of command /LotteryPlus version.
    default: op
  lotteryplus.command.lottery:
    description: Allows use of command /LotteryPlus lottery.
    default: op
  lotteryplus.lottery.*:
    description: To get the highest lottery chance.
    default: op
    children:
      lotteryplus.lottery.1: true
      lotteryplus.lottery.2: true
      lotteryplus.lottery.3: true
  lotteryplus.lottery.1:
    description: To get the higher lottery chance.
    default: op
  lotteryplus.lottery.2:
    description: To get the higher lottery chance.
    default: op
  lotteryplus.lottery.3:
    description: To get the higher lottery chance.
    default: op