# ░░░░░░░░░░░░░░░   LotteryPlus, By Momocraft♥   ░░░░░░░░░░░░░░░
#  Spigot: https://www.spigotmc.org/resources/entityplus.85995/
#  Wiki: https://github.com/momoservertw/LotteryPlus/wiki
# ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
Config-Version: 4
Debugging: false
Check-Updates: true

# Randomly select a reward for player.
# You can use ItemJoin to create one-use items.
# Or using with menu plugins like ChestCommands or BossShop.
# Lottery command: /lotteryplus lottery <groupName>
# More information: https://github.com/momoservertw/LotteryPlus/wiki/Lottery
Lottery:
  Enable: false
  Settings:
    Features:
      # Executing lottery when player broke a lucky block.
      Lucky-Block: false
      # The proportion of different player groups.
      # Permission: lotteryplus.lottery.chancegroup.GROUP
      Priority:
        default: 0
        vip: 1
        mvp: 2
    # Add logs when lottery.
    Log: true
  Groups:
    ticket:
      Enable: false
      Rewards:
        Normal:
          Enable: true
          Chance: 0.8
          Commands:
            - "message: &eYou win iron_ingot x16.{n}console: give %player% iron_ingot 16"
            - "message: &eYou win gold_ingot x16.{n}console: give %player% gold_ingot 16"
            - "message: &eYou win some money!{n}console: money give %player% %random_number%500%"
        Rare:
          Enable: true
          Chance: 0.2
          Commands:
            - "broadcast: &a%player% &ewin iron_ingot x64.{n}console: give %player% iron_ingot 64"
            - "broadcast: &a%player% &ewin gold_ingot x64.{n}console: give %player% gold_ingot 64"
            - "broadcast: &a%player% &ewin $10,000!{n}console: money give %player% 10000"
    random_head:
      Enable: false
      Rewards:
        online_players:
          Enable: true
          # Setting difference change for groups.
          # You have to set their "Priority" above.
          Chance:
            default: 0.9
            vip: 0.7
          Commands:
            - "message: &eYou win a random online player's head!{n}console: give %player% minecraft:player_head{SkullOwner:\"%random_player%\"} 1"
        staff:
          Enable: true
          Chance:
            default: 0.1
            vip: 0.3
          Commands:
            - "broadcast: &a%player% &ewin \"Momo_Darkness\"'s head!{n}console: give %player% minecraft:player_head{SkullOwner:\"Momo_Darkness\"} 1"
    lucky_block:
      Enable: false
      Settings:
        Lucky-Block:
          # More skull(copy the Value): https://minecraft-heads.com/custom-heads
          # Example: https://minecraft-heads.com/custom-heads/miscellaneous/25606-emoticon-in-strange-love
          Skull-Textures: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDI3MzdlOTllNGMwNTk2YTM3MTJlNzcxMWJhZWNhZThkMWRkYjc3NGFjMWNmNTMxODk2ODYyMzgwNzUzZTE2In19fQ=="
      Rewards:
        iron_ingot:
          Enable: true
          Chance: 0.5
          Commands:
            - "custom: Rewards, iron_ingot x64{n}console: give %player% IRON_INGOT 64"